version: '3'

services:
  web:
    build: todos_app
    ports:
      - '5000:5000'
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      SENDGRID_KEY: ${SENDGRID_KEY}
      VERIFY_EMAIL_URL: ${VERIFY_EMAIL_URL}
      PASSWORD_RESET_URL: ${PASSWORD_RESET_URL}

    volumes:
      - ./todos_app:/app

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
