"""adding a user account verification column

Revision ID: 6c09c4e12341
Revises: fea9c166309c
Create Date: 2022-02-25 14:22:07.325639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c09c4e12341'
down_revision = 'fea9c166309c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('verified', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'verified')
    # ### end Alembic commands ###
