"""creating todos table

Revision ID: ba3063031a1e
Revises: ba4d24c30f4c
Create Date: 2021-10-22 17:38:39.775445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3063031a1e'
down_revision = 'ba4d24c30f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('todo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Todos')
    # ### end Alembic commands ###
