os: linux
dist: xenial
language: python
python:
- 3.8.10
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE todos_test_db;" -U postgres
- psql -c "CREATE USER kiarie WITH PASSWORD '7194';" -U postgres
env:
  matrix:
  - TEST_DATABASE_URL="postgres://kiarie:7194@localhost/todos_test_db"
  global:
  - secure: VBv6e6lA+lyQFf3AYvrNSpzM9PT/lXqwSoFJcVeejpDXVgmGlTxBq2qwmXyykpMMDVX4p5CE82ufdcDmHCNluXHfcOh1rO6dLP4iAv/Fty5WHmYYF2tDT1D+sJZx44+Ev+WgTxNSrmqlfotfNRsvb1fvENlBxdx7hbNC2ou/Ku9MeJmHAmhlZTePPK0T8lpcKCZlwP+1WvLj1HP9G8qu3gAGTJksZ8O+jFlnC9LR4S8KoVNnTgC6TFs77L9VJUkuzoI+fgGKM2LU1+r+2hQdiT2nycVHc8RFa53qINokiz1jVkfv5++klBbOhp28C4UdQbfTQcedrKpGDzcAKCBkOgqx1+7Oy96YLGulzrAiuvL5iSsc7GdLOo3GRQLoeQpVsSxlWhl/qIiv40Yja1doFGp4MNb7SZ2auXd6bBrJQIZBRq8RzmtHmPRe3THWh/7Z0dgQJNi3K8YGvLGVephWjqNBoO4wG888O7v0VpIMqb42M5X9B1mUutt7WNgGpzWCa6bjgWr/x09QretHBL1mXsbKpFioa2vjIpQaCEWYsjMU8R/X63CeKi0rlvL8tkRru0V44xz4uouvMLTkOqk/RtitdALB2fZ3jAuGons+pKJYkZRaFffl4wVNpzQ+E9HUyWzOlR+ndGcLSWQRaTXS/nKssO9BnHudeOqsDuPAafQ=
script:
- python -m pytest --cov=app/api
after_success:
- coveralls
- bash <(curl -s https://codecov.io/bash)
